from modules.llm import prompt_local

develop_prompt = """
Instructions
You just retrieved new Evidence. Now, analyze the Claim's veracity using the evidence. Always adhere to the following rules:
- Focus on developing new insights. Do not repeat larger parts from the Record. Do not restate the Claim.
- Write down your thoughts step-by-step. Whenever necessary, you may elaborate in more detail.
- Depending on the topic's complexity, invest one to three paragraphs. The fewer, the better.
- If you find that there is insufficient information to verify the Claim, explicitly state what information is missing.
- If you cite web sources, always refer to them by including their URL as a Markdown hyperlink.
- Use information only from the recorded evidence:
- Avoid inserting information that is not implied by the evidence. You may use commonsense knowledge, though.

If it is extremely necessary to retrieve more evidence, you can propose actions to the user. If not necessary, do not add anything else other than the reasoning.

Adhere to the following rules:
- The actions available are listed under Valid Actions, including a short description for each action. No other actions are possible at this moment.
- For each action, use the formatting as specified in Valid Actions.
- Propose as few actions as possible but as much as needed. Do not propose similar or previously used actions.
- Include all actions in a single Markdown code block at the end of your answer.

Valid Actions:
web search: Run an open web search for related webpages.

Examples:
web_search("New Zealand Food Bill 2020")

Record:
{record}

Your Analysis:
"""

def develop(record, think=True):
    """
    Develops an analysis of the claim using the provided record.

    Args:
        record (str): The record containing evidence for the analysis.
        think (bool): Whether to use chain-of-thought (default True)
    Returns:
        str: The analysis generated by the LLM.
    """
    prompt = develop_prompt.format(record=record)
    return prompt_local(
        prompt,
        think=False,
        max_new_tokens=256,
        do_sample=False,
    )
